{% set name = "Lifetimes" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96c251e235db1efe23c49593e437431ad301ca7de6fcd909ebae19f3ea50247b

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - autograd >=1.2.0
    - dill >=0.2.6
    - numpy >=1.10.0
    - pandas >=0.24.0
    - python
    - scipy >=1.0.0
    - setuptools

test:
  imports:
    - lifetimes
    - lifetimes.datasets

about:
  home: https://github.com/CamDavidsonPilon/lifetimes
  license: MIT
  license_family: MIT
  license_file: README.md
  summary: Measure customer lifetime value in Python
  doc_url: https://lifetimes.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - CamDavidsonPilon
    - Arnoldosmium
